
#' Adds first/second/other era data to a processed regimen alignment ouput
#' @param pa A dataframe processed alignments, generated by processAlignments()
#' @param discontinuationTime The number of days to use to indicate treatment discontinuation
#' @return A processed alignment dataframe with added era data relating to first/second/other sequencing
#' @importFrom dplyr row_number lag
#' @export
calculateEras <- function(pa, discontinuationTime = 120) {
    # In case there are multiple patients in the dataframe
    # run eras for each patient separately
    patients = unique(pa$personID)

    if (length(patients) == 0) {
       cli::cat_bullet(
            paste("No patients found in input dataframe", sep = ""),
            bullet_col = "yellow",
            bullet = "info"
        )    
        return(data.frame())
    }
    
    pa_eras = list()    
    for (p in patients) {
        pa_s <- pa %>%
            filter(personID == p)

        pa_s <- calculateEras_one(pa_s, discontinuationTime = discontinuationTime)
        pa_eras[[as.character(p)]] = pa_s
    }

    pa_eras <- dplyr::bind_rows(pa_eras)
    return(pa_eras)
}

calculateEras_one <- function(pa, discontinuationTime = 120) {
    if (nrow(pa) == 0) {
        return(pa)
    }

    # Calculate eras for a single patient    
    pa <- pa[order(pa$t_start), ]
    toRemove <- c()

    # Combine overlaps could introduce overlapping regimens again as the time is often very long. 
    # Here we check if there are any overlaps left and remove the regimen that starts later.
    # In some cases, this removes better regimens. 
    if (nrow(pa) > 1) {
        for (ic in c(2:nrow(pa))) {
            if (pa[ic, ]$t_start < pa[ic - 1, ]$t_end) {
                toRemove <- c(toRemove, ic)
            }
        }
    }
        
    if (length(toRemove) > 0) {
        pa <- pa[-toRemove, ]
    }
        
    pa <- pa %>%
        dplyr::mutate(timeToNextRegimen = dplyr::lead(t_start) - t_end)

    # if the time gap between two consecutive regimens is smaller than discontinuationTime,
    # and they are the same regimen:
    # they are considered part of the same era (annotated as First_Line = 1)
    # otherwise, they are considered separate eras Second_Line = 1)
    # all subsequent eras are annotated as Other = 1
    
    pa <- pa %>%
        dplyr::mutate(
            same_era = ifelse((
                lag(timeToNextRegimen) < discontinuationTime &
                    component == dplyr::lag(component)
            ),
            "Y",
            "N"
            )
        )
    
    pa[1, ]$same_era <- "N"
    pa <- pa %>%
        dplyr::mutate(eras = cumsum(same_era == "N")) %>%
        dplyr::summarise(
            regCode = dplyr::first(regCode),
            cohort_start_date = dplyr::first(cohort_start_date),
            cohort_end_date = dplyr::first(cohort_end_date),
            first_drug_exposure_day = dplyr::first(first_drug_exposure_day),
            adjustedS = sum(adjustedS * (t_end - t_start) / max(sum(t_end - t_start), 1)), # avoid division by zero
            t_start = min(t_start),
            t_end = max(t_end),
            timToEod = min(timeToEOD),
            .by = c(component, eras, personID, DrugRecord_full)
        ) %>%
        dplyr::mutate(
            regLength = t_end - t_start,
            timeToNextRegimen = max(lag(t_start, 1) - t_end, 0),
            First_Line = 1 * (row_number() == 1),
            Second_Line = 1 * (row_number() == 2),
            Other = 1 * (row_number() > 2)
        )

    return(pa)    
}
