#' Creates cumulative times for each drug in the drug record
#' @param drugRec A drug record
#' @export
#' @return A data.table object with drugs
#'
createDrugDF <- function(drugRec){
  drugDF <- as.data.frame(t(as.data.frame(drugRec, col.names = c(seq(1:length(drugRec))))))
  names(drugDF) <- c("t_gap", "component")
  drugDF[1,]$t_gap <- 0

  # Assign each individual drug an occurrence period of roughly one day
  drugDF$t_start <- cumsum(drugDF$t_gap)
  drugDF$index <- 1:length(drugDF$t_gap)

  return(drugDF)

}

#' Calculates the number of unique aligned drugs in a regimen
#'
no_unique_aligned_drugs <- function(regimen) {
    s = gsub("[0-9]*\\.", "", regimen)
    
    s = unlist(strsplit(s, ";|~"))
    s = s[s!="__"]

    return(length(unique(s)))
}

#' Prepare data.frame for postproccessing. 
#' Adds cumulative times from drugDF to the dataframe,
#' where each regimen starts and ends
#' @param df A dataframe with drugRec_Start and drugRec_End columns
#' @param drugDF A drugDF object generated by createDrugDF()
#' @return A data.table object without removed overlaps
#' 
add_cumultive_times_to_df <- function(df, drugDF) {
    # Ensure drugRec_Start and drugRec_End are within valid range
    df <- df %>%
      dplyr::mutate(drugRec_Start = pmax(drugRec_Start, 1),
                    drugRec_End   = pmin(drugRec_End, max(drugDF$index))
      )
 
    # Add cumulative times to the dataframe
    df$t_start <- drugDF[df$drugRec_Start,]$t_start
    df$t_end <- drugDF[df$drugRec_End,]$t_start
    
    return(df)
}

#' Removes overlapping regimens from alignment output
#'
#' Two overlap removal steps are performed:
#' #' 1. Remove overlaps between regimens with different names  
#' #' 2. Remove overlaps between regimens with different number of components
#' @param df A dataframe created by align() with cumulative times added by add_cumultive_times_to_df()
#' @return A data.table object without removed overlaps
#' @importFrom data.table :=
#' @importFrom data.table .I
#' 
removeOverlaps <- function(df) {
    # get number of components in each regimen variant
    regCount <- df %>%
        dplyr::rowwise() %>%
        dplyr::mutate(
            compNo = no_unique_aligned_drugs(Regimen) 
        ) %>%
        dplyr::select(regName, Regimen, compNo) %>% 
        dplyr::distinct()

    # Convert to data.table to do overlap and drop lower scored regimens
    data.table::setDT(df)
    data.table::setorder(df, drugRec_Start, drugRec_End)
    df[, index := .I]
    
    df_overlap <- data.table::copy(df)
    data.table::setkey(df_overlap, drugRec_Start, drugRec_End)
    
    # Find overlaps where regName is different
    overlaps <- data.table::foverlaps(df, df_overlap, nomatch = 0, 
                          by.x = c("drugRec_Start", "drugRec_End"), 
                          by.y = c("drugRec_Start", "drugRec_End"))
    overlaps <- overlaps[regName != i.regName & index < i.index]
    removed <- integer(0)
    
    # Process overlaps row-wise and remove lower scored regimens
    for (row in seq_len(nrow(overlaps))) {
        i <- overlaps$index[row]
        j <- overlaps$i.index[row]
        
        if (i %in% removed || j %in% removed) next
        
        i_score <- overlaps$adjustedS[row]
        j_score <- overlaps$i.adjustedS[row]
        
        if (i_score < j_score) {
            removed <- c(removed, i)
        } else if (j_score < i_score) {
            removed <- c(removed, j)
        }
    }
    
    df <- df[!index %in% removed]
    df[, index := NULL]

    # SECOND overlap removal - removing low component high scoring regimens
    # compNo - number of components
    data.table::setDT(regCount)
    df <- merge(df, regCount, by = c("regName", "Regimen"))
    df[, index := .I]
    data.table::setorder(df, t_start, t_end)
    df_overlap <- data.table::copy(df)
    data.table::setkey(df_overlap, t_start, t_end)

    overlaps <- data.table::foverlaps(df, df_overlap, nomatch = 0, 
                          by.x = c("t_start", "t_end"), 
                          by.y = c("t_start", "t_end"))
    
    # Exclude self-overlaps
    overlaps <- overlaps[index != i.index]
    toRemove <- overlaps[compNo != i.compNo, 
                         .(remove = ifelse(compNo < i.compNo, index, i.index))]$remove
    
    df <- df[!index %in% toRemove]    

    df <- as.data.frame(df)
    return(df)
}

#' Combine Overlaps
#' 
#' Merge overlapping regimens in alignment output.
#' Regimens are only merged if they are identical and occur consecutively in time.
#' @param output An output dataframe created by align()
#' @param regimenCombine Allowed days between same regimen before being combined
#' 
combineOverlaps <- function(df, regimenCombine) {
    # Create id for consecutive regimens and remove if distance is larger than regimenCombine
    dt <- df
    data.table::setDT(dt)
    # TODO: remove regName to disable regimen overlap 
    data.table::setorder(dt, regName, t_start, t_end)

    # use cumulative max time, in case previous regimen extended further
    dt[, t_end := cummax(t_end), by = regName]

    dt[, run_id := cumsum(
        c(TRUE, regName[-1] != regName[-.N] | (t_start[-1] - t_end[-.N]) >= regimenCombine)
    )]
    
    dt <- dt[, .(
              drugRec_Start = min(drugRec_Start),
              drugRec_End   = max(drugRec_End),
              t_start       = min(t_start),
              t_end         = max(t_end),
              adjustedS     = mean(adjustedS),
              Score         = mean(Score),
              totAlign      = sum(totAlign)
            ), by = .(personID, regName, run_id, CompleteDrugRecord)
            ][, run_id := NULL][, component := regName]


      return(as.data.frame(dt))
}



#' Adds line of treatment to a processed regimen alignment ouput
#' @param pa A dataframe processed alignments, generated by processAlignments()
#' @param drugDF A drugDF object generated by createDrugDF()
#' @param discontinuationTime The number of days to use to indicate treatment discontinuation
#' @return A processed alignment dataframe with added era data relating to first/second/other sequencing
#' @importFrom dplyr row_number lag case_when mutate group_by summarise lead arrange select
lineOfTreatment <- function(pa, drugDF, discontinuationTime = 120) {
    if (nrow(pa) == 0) {
        return(pa)
    }

    # Calculate time to next regimen (start of the next regimen minus start of current regimen), 0 if negative
    # Calculate interval between regimens (start of the next regimen minus end of current regimen), 0 if negative
    # Calculate regimen length

    pa <- pa %>%
        arrange(t_start) %>%
        mutate(timeToNextRegimen = pmax(0, lead(t_start, default = 0) - t_start)) %>%
        mutate(interval = pmax(0, lead(t_start, default = 0) - t_end)) %>%
        mutate(regLength = (t_end - t_start) + 1)    
    
    # The last interval is the time between the end of the last regimen and the end of the drug record, 
    final_time <- max(drugDF$t_start)
    pa[nrow(pa),]$interval <- final_time - pa[nrow(pa),]$t_end
    # if the time gap between two consecutive regimens is smaller than discontinuationTime,
    # and they are the same regimen:
    # they are considered part of the same line of treatment
    # otherwise, they are considered separate eras Second_Line = 1)
    # all subsequent eras are annotated as Other = 1
    
    pa <- pa %>%
        mutate(
            same_line = ifelse((
                lag(timeToNextRegimen) < discontinuationTime &
                    lag(component) == component
            ),
            "Y",
            "N"
            )
        )
    
    pa[1, ]$same_line <- "N"

    # Combine regimens into lines of treatment, and calculate line of treatment metrics
    pa <- pa %>%
        mutate(lines = cumsum(same_line == "N")) %>%
        summarise(
            adjustedS = sum(adjustedS * max(t_end - t_start, 1) / max(sum(t_end - t_start), 1)), # avoid division by zero
            t_start = min(t_start),
            t_end = max(t_end),
            interval = min(interval),
            .by = c(component, lines, personID, CompleteDrugRecord)
        ) %>%
        mutate(
            regLength = t_end - t_start,
            timeToNextRegimen = pmax(0, lead(t_start, default = 0) - t_start),
            lineOfTreatment = case_when(
                lines == 1 ~ "first",
                lines == 2 ~ "second",
                lines  > 2 ~ "other"
            )
        ) %>%   
        select(-lines)
    

    return(pa)    
}


#' Postprocess alignment output
#'
#' @param output An output dataframe created by align()
#' @param regimenCombine Allowed number of days between two instances of the same regimen before
#' @param discontinuationTime The number of days to use to indicate treatment discontinuation treshold for line of treatment annotation
#' @return df - A data.frame object
#' 
postprocessSinglePatientDF <- function(output, regimenCombine = 28, discontinuationTime = regimenCombine) {
    # Remove rows with NA score and low scoring or one drug alignments  
    df <- output %>% 
        dplyr::filter(totAlign > 1 & adjustedS > 0.501)

    if (nrow(df) == 0) {
        return(data.frame())
    }  

    # Use patient drug record to create cumulative times
    # Assume drug record is the same for all rows
    drugRec <- encode(df$CompleteDrugRecord[1])
    drugDF <- createDrugDF(drugRec)

    df <- add_cumultive_times_to_df(df, drugDF)    
    df <- removeOverlaps(df)
    df <- combineOverlaps(df, regimenCombine)

    df <- df %>%
        dplyr::arrange(t_start)

    # Combine overlaps could introduce overlapping regimens again as the time is often very long. 
    # Here we check if there are any overlaps left and remove the regimen that starts later.
    # In some cases, this removes better regimens. 
    toRemove <- c()
    if (nrow(df) > 1) {
        for (ic in c(2:nrow(df))) {
            if (df[ic, ]$t_start < df[ic - 1, ]$t_end) {
                toRemove <- c(toRemove, ic)
            }
        }
    }
        
    if (length(toRemove) > 0) {
        df <- df[-toRemove, ]
    }

    df <- lineOfTreatment(df, drugDF, discontinuationTime = discontinuationTime)

  return(df)                
}


#' Post-process alignment output
#' 
#' Perform post-processing on a data frame of raw alignment results. Three main steps are performed:
#' 1. Remove overlaps between regimens
#' 2. Combine regimens
#' 3. Calculate additional time-based metrics and line of treatment. 
#' @param ra Raw alignments. An output dataframe produced by generateRawAlignments()
#' @param regimenCombine The numeric value of days allowed between regimens of the same
#' name before they are collapsed/summarised into a single regimen
#' @param discontinuationTime The number of days to use to indicate treatment discontinuation treshold for line of treatment annotation. Default is the same as regimenCombine, but can be set higher to allow for longer gaps between lines of treatment.
#' @return A dataframe processed alignments
#' @export
processAlignments <- function(ra,
                              regimenCombine,
                              discontinuationTime = regimenCombine
                             ) {

    if (nrow(ra) == 0) {
        cli::cat_bullet(
            paste("No alignments detected", sep = ""),
            bullet_col = "yellow",
            bullet = "info"
        )
        return(data.frame()) 
    }

    IDs_All <- unique(ra$personID)    
    cli::cat_bullet(
        paste(
            "Performing post-processing of ", length(IDs_All),
            " patients.\n Total alignments: ", dim(ra)[1],
            sep = ""
        ),
        bullet_col = "yellow",
        bullet = "info"
    )
    
    # Postprocess each patient individually
    pa <- data.frame()

    for (i in c(1:length(IDs_All))) {
        ra_s <- ra %>%
            filter(personID == IDs_All[i])
        
        pa_s <- postprocessSinglePatientDF(ra_s, 
                                           regimenCombine = regimenCombine, 
                                           discontinuationTime = discontinuationTime)

        pa <- dplyr::bind_rows(pa, pa_s)   
        progress(x = i, max = length(IDs_All))
    }
    
    cli::cat_bullet("Complete!",
                    bullet_col = "green",
                    bullet = "tick")
    
    return(pa)
    
}
