
#' Generate Regimen Stats
#' 
#' Generates a data frame containing summary stats from processed regimen data.
#' @param processedEras A dataframe processed alignments, generated by processAlignments()
#' @return A data frame containing summary stats from processed regimen data
#' @export
generateRegimenStats <- function(processedEras) {
    processedEras$t_total <- (processedEras$t_end - processedEras$t_start) +
        1
    
    meanScores <- aggregate(adjustedS ~ component, processedEras, mean)
    medianScores <- aggregate(adjustedS ~ component, processedEras, median)
    rangeScores <- aggregate(adjustedS ~ component, processedEras, range)
    rangeScores$rangeScores <- paste("(", rangeScores[, 2][, 1], "-", rangeScores[, 2][, 2], ")", sep =
                                         "")
    rangeScores <- rangeScores[, c(1, 3)]
    colnames(rangeScores) <- c("component", "rangeScores")
    
    meanTimes <- aggregate(t_total ~ component, processedEras, mean)
    medianTimes <- aggregate(t_total ~ component, processedEras, median)
    rangeTimes <- aggregate(t_total ~ component, processedEras, range)
    rangeTimes$rangeTimes <- paste("(", rangeTimes[, 2][, 1], "-", rangeTimes[, 2][, 2], ")", sep =
                                       "")
    rangeTimes <- rangeTimes[, c(1, 3)]
    colnames(rangeTimes) <- c("component", "rangeTimes")
    
    firstLikelihood <- aggregate(First_Line ~ component, processedEras, mean)
    secondLikelihood <- aggregate(Second_Line ~ component, processedEras, mean)
    otherLikelihood <- aggregate(Other ~ component, processedEras, mean)
    
    count <- as.data.frame(table(processedEras$component))
    frequency <- as.data.frame(table(processedEras$component) / sum(table(processedEras$component)))
    colnames(count) <- c("component", "count")
    colnames(frequency) <- c("component", "frequency")
    
    dim(merge(meanScores, medianScores))
    
    aggregated_Processed_Data <- merge(merge(merge(
        merge(
            merge(
                merge(
                    merge(merge(
                        merge(
                            merge(meanScores, medianScores, by = "component"),
                            rangeScores,
                            by = "component"
                        ), meanTimes, by = "component"
                    ), medianTimes, by = "component"),
                    rangeTimes,
                    by = "component"
                ),
                firstLikelihood,
                by = "component"
            ),
            secondLikelihood,
            by = "component"
        ),
        otherLikelihood,
        by = "component"
    ), count, by = "component"), frequency, by = "component")
    colnames(aggregated_Processed_Data) <- c(
        "regName",
        "Mean Score",
        "Median Score",
        "Score Range",
        "Mean Length of Treatment",
        "Median Length of Treatment",
        "Length of Treatment Range",
        "First Era Likelihood",
        "Second Era Likelihood",
        "Other Era Likelihood",
        "Count",
        "Frequency"
    )
    return(aggregated_Processed_Data)
}


#' Generate several stats related to the input cohort
#' @param connectionDetails A set of DatabaseConnector connectiondetails
#' @param cdmSchema A schema containing a valid OMOP CDM
#' @param stringDF A stringDF object containing all valid patients (i.e., those who have exposure
#' to at least one valid drug)
#' @param con_df A con_df dataframe
#' @return A dataframe containing various summary statistics regarding the age of treated
#' and untreated patients
#' @export
generateCohortStats <- function(connectionDetails,
                                cdmSchema,
                                con_df,
                                stringDF) {
    connection <- DatabaseConnector::connect(connectionDetails = connectionDetails)
    
    subjects <- unique(con_df$person_id)
    
    con_df_filtered <- con_df[!con_df$person_id %in% stringDF$person_id, ]
    subjects_filtered <- unique(con_df_filtered$person_id)
    subjects_unfiltered <- subjects[!subjects %in% subjects_filtered]
    
    person <- dplyr::tbl(connection,
                         DatabaseConnector::inDatabaseSchema(cdmSchema, "person"))
    
    con_patientTable <- person %>%
        dplyr::filter(.data$person_id %in% subjects) %>%
        dplyr::select(.data$person_id,
                      .data$year_of_birth,
                      .data$gender_concept_id) %>%
        as.data.frame()
    
    con_patientTable$gender <- ifelse(con_patientTable$gender_concept_id ==
                                          "8532", "F", "M")
    con_patientTable$age <- 2022 - as.numeric(as.character(con_patientTable$year_of_birth))
    
    unTreated <- con_patientTable %>%
        dplyr::filter(.data$person_id %in% subjects_filtered) %>%
        dplyr::select(.data$person_id, .data$age, .data$gender)
    
    uQuants_m <- quantile(unTreated[unTreated$gender == "M", ]$age)[c(2, 3, 4)]
    uQuants_f <- quantile(unTreated[unTreated$gender == "F", ]$age)[c(2, 3, 4)]
    uQuants_t <- quantile(unTreated$age)[c(2, 3, 4)]
    
    treated <- con_patientTable %>%
        dplyr::filter(.data$person_id %in% subjects_unfiltered) %>%
        dplyr::select(.data$person_id, .data$age, .data$gender)
    
    tQuants_m <- quantile(treated[treated$gender == "M", ]$age)[c(2, 3, 4)]
    tQuants_f <- quantile(treated[treated$gender == "F", ]$age)[c(2, 3, 4)]
    tQuants_t <- quantile(treated$age)[c(2, 3, 4)]
    
    quantiles <- as.data.frame(rbind(uQuants_t, rbind(tQuants_t, rbind(
        tQuants_m, rbind(tQuants_f, rbind(uQuants_m, uQuants_f))
    ))))
    quantiles$Category <- c("Untreated",
                            "Treated",
                            "Treated",
                            "Treated",
                            "Untreated",
                            "Untreated")
    quantiles$Gender <- c("Total", "Total", "M", "F", "M", "F")
    
    colnames(quantiles) <- c(
        "25th Percentile (AGE)",
        "Median (AGE)",
        "75th Percentile (AGE)",
        "Category",
        "Gender"
    )
    
    quantiles <- reshape2::melt(quantiles)
    quantiles$variable <- as.character(quantiles$variable)
    quantiles <- rbind(quantiles, c("Untreated", "Total", "No. of Patients", dim(unTreated)[1]))
    quantiles <- rbind(quantiles, c("Treated", "Total", "No. of Patients", dim(treated)[1]))
    quantiles <- rbind(quantiles, c("Treated", "M", "No. of Patients", dim(treated[treated$gender ==
                                                                                       "M", ])[1]))
    quantiles <- rbind(quantiles, c("Treated", "F", "No. of Patients", dim(treated[treated$gender ==
                                                                                       "F", ])[1]))
    quantiles <- rbind(quantiles, c("Untreated", "M", "No. of Patients", dim(unTreated[unTreated$gender ==
                                                                                           "M", ])[1]))
    quantiles <- rbind(quantiles, c("Untreated", "F", "No. of Patients", dim(unTreated[unTreated$gender ==
                                                                                           "F", ])[1]))
    
    output_df <- reshape2::acast(quantiles, variable ~ Gender + Category, value.var = "value")
    
    drug_exposure <- dplyr::tbl(connection,
                                DatabaseConnector::inDatabaseSchema(cdmSchema, "drug_exposure"))
    concept_ancestor <- dplyr::tbl(
        connection,
        DatabaseConnector::inDatabaseSchema(cdmSchema, "concept_ancestor")
    )
    concept <- dplyr::tbl(connection,
                          DatabaseConnector::inDatabaseSchema(cdmSchema, "concept"))
    
    con <- drug_exposure %>%
        dplyr::filter(.data$person_id %in% subjects_filtered) %>%
        dplyr::select(c("person_id", "drug_concept_id")) %>%
        dplyr::distinct() %>%
        dplyr::left_join(concept_ancestor,
                         by = c("drug_concept_id" = "descendant_concept_id")) %>%
        dplyr::left_join(concept, by = c("ancestor_concept_id" = "concept_id")) %>%
        dplyr::filter(tolower(.data$concept_class_id) == "atc 1st")
    
    con_df_temp <- as.data.frame(con)
    
    con_df_m <- con_df_temp %>%
        dplyr::filter(.data$person_id %in% unTreated[unTreated$gender == "M", ]$person_id)
    
    con_df_f <- con_df_temp %>%
        dplyr::filter(.data$person_id %in% unTreated[unTreated$gender == "F", ]$person_id)
    
    m_df <- as.data.frame(table(con_df_m$concept_name) / sum(table(con_df_m$concept_name)))
    f_df <- as.data.frame(table(con_df_f$concept_name) / sum(table(con_df_f$concept_name)))
    t_df <- as.data.frame(table(con_df_temp$concept_name) / sum(table(con_df_temp$concept_name)))
    
    m_df$Category <- "Untreated"
    m_df$Gender <- "M"
    f_df$Category <- "Untreated"
    f_df$Gender <- "F"
    t_df$Category <- "Untreated"
    t_df$Gender <- "Total"
    
    colnames(m_df)[c(1, 2)] <- c("variable", "value")
    colnames(f_df)[c(1, 2)] <- c("variable", "value")
    colnames(t_df)[c(1, 2)] <- c("variable", "value")
    
    atc_output <- as.data.frame(reshape2::acast(rbind(t_df, rbind(m_df, f_df)), variable ~
                                                    Gender + Category, value.var = "value"))
    atc_output$M_Treated <- ""
    atc_output$F_Treated <- ""
    atc_output$Total_Treated <- ""
    atc_output <- atc_output[, c(5, 1, 4, 2, 6, 3)]
    
    output <- rbind(output_df, atc_output)
    
    output[c(5:18), ]$F_Untreated <- as.character(format(round(
        100 * as.numeric(output[c(5:18), ]$F_Untreated), 2
    ), nsmall = 2))
    output[c(5:18), ]$M_Untreated <- as.character(format(round(
        100 * as.numeric(output[c(5:18), ]$M_Untreated), 2
    ), nsmall = 2))
    output[c(5:18), ]$Total_Untreated <- as.character(format(round(
        100 * as.numeric(output[c(5:18), ]$Total_Untreated), 2
    ), nsmall = 2))
    
    return(output)
    
}