
#' Generate Regimen Stats
#' 
#' Generates a data frame containing summary stats from processed regimen data.
#' @param pa A dataframe processed alignments, generated by processAlignments()
#' @return A data frame containing summary stats from processed regimen data
#' importFrom dplyr group_by summarise full_join count pivot_wider 
#' @export
generateRegimenStats <- function(pa) {
    pa$t_total <- (pa$t_end - pa$t_start) + 1

    stats_score <- pa %>% 
        group_by(component) %>% 
        summarise(
                meanScores = mean(adjustedS), 
                medianScores = median(adjustedS),
                rangeScores = paste(round(range(adjustedS), 2), collapse = "-")
                )

    stats_time <- pa %>% 
        group_by(component) %>% 
        summarise(
                meanTimes = mean(t_total), 
                medianTimes = median(t_total),
                rangeTimes = paste(round(range(t_total), 2), collapse = "-")
        )

    stats_line <- pa %>% 
        count(component, lineOfTreatment) %>% 
        pivot_wider(id_cols = component, 
                    names_from = lineOfTreatment, 
                    names_prefix = "lineOfTreatment_",
                    values_from = n, values_fill = 0)


    stats = stats_score %>% 
        full_join(stats_time, by = "component") %>% 
        full_join(stats_line, by = "component")

    return(stats)
}


#' Generate several stats related to the input cohort
#' @param connectionDetails A set of DatabaseConnector connectiondetails
#' @param cdmSchema A schema containing a valid OMOP CDM
#' @param stringDF A stringDF object containing all valid patients (i.e., those who have exposure
#' to at least one valid drug)
#' @param con_df A con_df dataframe
#' @return A dataframe containing various summary statistics regarding the age of treated
#' and untreated patients
#' @export
generateCohortStats <- function(connectionDetails,
                                cdmSchema,
                                con_df,
                                stringDF) {
    connection <- DatabaseConnector::connect(connectionDetails = connectionDetails)
    
    subjects <- unique(con_df$person_id)
    
    con_df_filtered <- con_df[!con_df$person_id %in% stringDF$person_id, ]
    subjects_filtered <- unique(con_df_filtered$person_id)
    subjects_unfiltered <- subjects[!subjects %in% subjects_filtered]
    
    person <- dplyr::tbl(connection,
                         DatabaseConnector::inDatabaseSchema(cdmSchema, "person"))
    
    con_patientTable <- person %>%
        dplyr::filter(.data$person_id %in% subjects) %>%
        dplyr::select(.data$person_id,
                      .data$year_of_birth,
                      .data$gender_concept_id) %>%
        as.data.frame()
    
    con_patientTable$gender <- ifelse(con_patientTable$gender_concept_id ==
                                          "8532", "F", "M")
    con_patientTable$age <- 2022 - as.numeric(as.character(con_patientTable$year_of_birth))
    
    unTreated <- con_patientTable %>%
        dplyr::filter(.data$person_id %in% subjects_filtered) %>%
        dplyr::select(.data$person_id, .data$age, .data$gender)
    
    uQuants_m <- quantile(unTreated[unTreated$gender == "M", ]$age)[c(2, 3, 4)]
    uQuants_f <- quantile(unTreated[unTreated$gender == "F", ]$age)[c(2, 3, 4)]
    uQuants_t <- quantile(unTreated$age)[c(2, 3, 4)]
    
    treated <- con_patientTable %>%
        dplyr::filter(.data$person_id %in% subjects_unfiltered) %>%
        dplyr::select(.data$person_id, .data$age, .data$gender)
    
    tQuants_m <- quantile(treated[treated$gender == "M", ]$age)[c(2, 3, 4)]
    tQuants_f <- quantile(treated[treated$gender == "F", ]$age)[c(2, 3, 4)]
    tQuants_t <- quantile(treated$age)[c(2, 3, 4)]
    
    quantiles <- as.data.frame(rbind(uQuants_t, rbind(tQuants_t, rbind(
        tQuants_m, rbind(tQuants_f, rbind(uQuants_m, uQuants_f))
    ))))
    quantiles$Category <- c("Untreated",
                            "Treated",
                            "Treated",
                            "Treated",
                            "Untreated",
                            "Untreated")
    quantiles$Gender <- c("Total", "Total", "M", "F", "M", "F")
    
    colnames(quantiles) <- c(
        "25th Percentile (AGE)",
        "Median (AGE)",
        "75th Percentile (AGE)",
        "Category",
        "Gender"
    )
    
    quantiles <- reshape2::melt(quantiles)
    quantiles$variable <- as.character(quantiles$variable)
    quantiles <- rbind(quantiles, c("Untreated", "Total", "No. of Patients", dim(unTreated)[1]))
    quantiles <- rbind(quantiles, c("Treated", "Total", "No. of Patients", dim(treated)[1]))
    quantiles <- rbind(quantiles, c("Treated", "M", "No. of Patients", dim(treated[treated$gender ==
                                                                                       "M", ])[1]))
    quantiles <- rbind(quantiles, c("Treated", "F", "No. of Patients", dim(treated[treated$gender ==
                                                                                       "F", ])[1]))
    quantiles <- rbind(quantiles, c("Untreated", "M", "No. of Patients", dim(unTreated[unTreated$gender ==
                                                                                           "M", ])[1]))
    quantiles <- rbind(quantiles, c("Untreated", "F", "No. of Patients", dim(unTreated[unTreated$gender ==
                                                                                           "F", ])[1]))
    
    output_df <- reshape2::acast(quantiles, variable ~ Gender + Category, value.var = "value")
    
    drug_exposure <- dplyr::tbl(connection,
                                DatabaseConnector::inDatabaseSchema(cdmSchema, "drug_exposure"))
    concept_ancestor <- dplyr::tbl(
        connection,
        DatabaseConnector::inDatabaseSchema(cdmSchema, "concept_ancestor")
    )
    concept <- dplyr::tbl(connection,
                          DatabaseConnector::inDatabaseSchema(cdmSchema, "concept"))
    
    con <- drug_exposure %>%
        dplyr::filter(.data$person_id %in% subjects_filtered) %>%
        dplyr::select(c("person_id", "drug_concept_id")) %>%
        dplyr::distinct() %>%
        dplyr::left_join(concept_ancestor,
                         by = c("drug_concept_id" = "descendant_concept_id")) %>%
        dplyr::left_join(concept, by = c("ancestor_concept_id" = "concept_id")) %>%
        dplyr::filter(tolower(.data$concept_class_id) == "atc 1st")
    
    con_df_temp <- as.data.frame(con)
    
    con_df_m <- con_df_temp %>%
        dplyr::filter(.data$person_id %in% unTreated[unTreated$gender == "M", ]$person_id)
    
    con_df_f <- con_df_temp %>%
        dplyr::filter(.data$person_id %in% unTreated[unTreated$gender == "F", ]$person_id)
    
    m_df <- as.data.frame(table(con_df_m$concept_name) / sum(table(con_df_m$concept_name)))
    f_df <- as.data.frame(table(con_df_f$concept_name) / sum(table(con_df_f$concept_name)))
    t_df <- as.data.frame(table(con_df_temp$concept_name) / sum(table(con_df_temp$concept_name)))
    
    m_df$Category <- "Untreated"
    m_df$Gender <- "M"
    f_df$Category <- "Untreated"
    f_df$Gender <- "F"
    t_df$Category <- "Untreated"
    t_df$Gender <- "Total"
    
    colnames(m_df)[c(1, 2)] <- c("variable", "value")
    colnames(f_df)[c(1, 2)] <- c("variable", "value")
    colnames(t_df)[c(1, 2)] <- c("variable", "value")
    
    atc_output <- as.data.frame(reshape2::acast(rbind(t_df, rbind(m_df, f_df)), variable ~
                                                    Gender + Category, value.var = "value"))
    atc_output$M_Treated <- ""
    atc_output$F_Treated <- ""
    atc_output$Total_Treated <- ""
    atc_output <- atc_output[, c(5, 1, 4, 2, 6, 3)]
    
    output <- rbind(output_df, atc_output)
    
    output[c(5:18), ]$F_Untreated <- as.character(format(round(
        100 * as.numeric(output[c(5:18), ]$F_Untreated), 2
    ), nsmall = 2))
    output[c(5:18), ]$M_Untreated <- as.character(format(round(
        100 * as.numeric(output[c(5:18), ]$M_Untreated), 2
    ), nsmall = 2))
    output[c(5:18), ]$Total_Untreated <- as.character(format(round(
        100 * as.numeric(output[c(5:18), ]$Total_Untreated), 2
    ), nsmall = 2))
    
    return(output)
    
}