# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
name: pkgdown.yaml

on:
  push:
    branches: [main]
    paths:
      - 'R/**'
      - 'man/**'
      - 'vignettes/**'
      - 'DESCRIPTION'
      - 'README.md'
      - '.github/workflows/pkgdown.yaml'
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  pkgdown:
    runs-on: ubuntu-22.04
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website
          cache: true
          cache-version: 1

      - name: Build site
        run: pkgdown::build_site(override = list(development = list(mode = "release")), new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Add vignette images
        run: cp -r vignettes/images docs/articles/images

      - name: Upload artifact 📦
        if: github.event_name != 'pull_request'
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'

      - name: Deploy to GitHub Pages 🚀
        if: github.event_name != 'pull_request'
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Print site URL 🔗
        if: github.event_name != 'pull_request'
        run: |
          echo "🔗 **[https://ohdsi.github.io/ARTEMIS/](https://ohdsi.github.io/ARTEMIS/)**" >> $GITHUB_STEP_SUMMARY